### ISSUE TITLE
Rye not building using Swift Package manager

### ISSUE THREAD

**Issue by jakobmygind** [nodes-ios/Rye#41] opened 2020-05-18 11:09 UTC
HI! For some reason RyePresentation doesn't recognise PassthroughWindow when integrating using SPM. Weirdly the issue can be fixed by moving the PassthroughWindow class out of its own file and into RyePresentation, so I guess it's some SPM idiosyncrasy? 

Steps to reproduce:

1. Make a new ios-project using Xcode 11.4.1
2. integrate Rye using SPM
3. try to build and observe compile errors

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/8362263/82206624-d6c14580-9908-11ea-9bda-0eca8cd6e1e5.png">

**Comment by chriscombs** [comment] 2020-05-18 11:28
Only on SPM, that's... interesting. I'll take a look tomorrow

**Comment by jakobmygind** [comment] 2020-05-18 11:43
> Only on SPM, that's... interesting. I'll take a look tomorrow

To be fair, I haven't actually tried Carthage, I just assumed that it would have been caught already if that didn't work 😬

**Comment by pbodsk** [comment] 2020-05-18 11:56
Hey @jakobmygind 

You have no idea how glad I am to see that you're stilly using Rye ❤️ 

Some observations

I can reproduce the error. 

If I go to the folder containing the checked out Rye package I can verify that `PassThroughWindow` actually _is not_ there (so no wonder it is complaining)

![Screenshot 2020-05-18 at 13 47 28](https://user-images.githubusercontent.com/117636/82210151-c8762800-990e-11ea-802e-00d0a814ab68.png)

As you can see, these files are linked/shortcuts. If I go to their original location I can see that `PassThroughWindow` _is present there_ 🤔 

![Screenshot 2020-05-18 at 13 48 47](https://user-images.githubusercontent.com/117636/82210219-e774ba00-990e-11ea-86b3-b8c8dd1c19f4.png)

So, the reason it works when you move it to `RyePresentation` is that this file is copied as expected....so yeah, definitely a fix, but I would like to find out _why_ it fails 😄 

I'm wondering if it is some sort of referencing/linking that fails.

**Comment by jakobmygind** [comment] 2020-05-18 12:52
@pbodsk Don't fix what ain't broken or can be ignored with appropriate amounts of alcohol, amirite?

Oho, good point, you know what? I think that when support was added for SPM symlinks to the files in the Package were manually added to the Sources folder where spm files seem to have to live, and since PassthroughWindow is a new file, the symlink was not yet created.. It seems a little brittle, there might be a way to employ some automation such that everything is in sync

https://developer.apple.com/documentation/xcode/creating_a_standalone_swift_package_with_xcode

**Comment by pbodsk** [comment] 2020-05-18 13:05
Bingo! @mariusc came to the same conclusion 30 minutes ago and that _was indeed_ the issue.

Agreed, its brittle and fragile. We should look into fixing that at some point.

For now I've made a `bugfix/link-passthrough-window` bugfix branch which works in my test project. Would you like to verify that it fixes the issue for you as well?....before I spin up the "make a new release" machine 😄

**Comment by jakobmygind** [comment] 2020-05-18 13:14
@pbodsk @mariusc  Swift action! (töhö)

That branch works, cheers!

**Comment by pbodsk** [comment] 2020-05-18 13:15
@jakobmygind Cool, I'll draft a new release tonight then.

Thanks 👍

**Comment by pbodsk** [comment] 2020-05-18 14:14
Fixed with https://github.com/nodes-ios/Rye/pull/42

**Closed by pbodsk** 2020-05-18 14:14 UTC
